### ISSUE TITLE
process.binding('evals') is deprecated, breaks on node 0.12.0

### ISSUE THREAD

**Issue by toomasp** [kanso/kanso-utils#2]
#2010.11.16 Version 0.3.1 (unstable), ce9a54

**API: Move process.binding('evals') to require('vm')**

**Comment by natevw** [comment]
For the record, this was fixed in https://github.com/kanso/kanso-utils/commit/c245a50c0930f4b691379b1c559b0581e2badc3e

A few other packages in this organization still have their own copy of this library, though.
